Import('env static_LIBS lib_NAME')

FILES = ['test.c',
         'karray.c',
         'kbuffer.c',
         'kerror.c',
         'khash.c',
         'klist.c',
         'kpath.c',
         'krb_tree.c',
         'kstr.c',
         'kserializable.c',
         'base64.c',
        ]

FILES.append(env.ExtractTests(source = FILES, target = "unit_test.c"))

OBJS = []
for s in FILES:
    OBJS.append(env.Object(s))

PROGS = [env.Program(target = 'test', source = OBJS + static_LIBS, LINKFLAGS='-rdynamic', LIBS=['dl','pthread'])]

Return('OBJS PROGS')
